[book]
authors = ["Kurt Rhee"]
language = "en"
multilingual = false
src = "src"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
site-url = "/docs-mdbook/"
additional-js = ["mermaid.min.js", "mermaid-init.js"]
additional-css = ["theme/card-layout.css", "theme/mermaid.css"]
